import os
DELTA_API_KEY=os.getenv("DELTA_API_KEY")
DELTA_API_SECRET=os.getenv("DELTA_API_SECRET")
TELEGRAM_BOT_TOKEN=os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID=os.getenv("TELEGRAM_CHAT_ID")
BASE_URL="https://api.india.delta.exchange/v2"
SYMBOLS=["BTCUSD","ETHUSD"]
VERSION="3.0"
PROJECT_NAME="NAKSHATRA AI CRYPTO"
